on: push

name: CI/CD

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workers: [ 10 ]
        worker_idx: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
    steps:
      - uses: actions/checkout@v2
      - uses: nixbuild/nix-quick-install-action@v2
        with:
          nix_version: 3.0pre20200829_f156513
          nix_conf: experimental-features = nix-command flakes
      - uses: nixbuild/nixbuild-action@v1
        with:
          nixbuild_ssh_key: ${{ secrets.nixbuild_ssh_key }}
      - name: eval nixpkgs
        id: eval-nixpkgs
        env:
          WORKERS: ${{ matrix.workers }}
          WORKER_IDX: ${{ matrix.worker_idx }}
        run: |
          nix eval --json --apply "f: f $WORKERS $WORKER_IDX" .#jobs > drvs.tmp
          jq -c ".[]" drvs.tmp > derivations.json
          echo "::set-output name=drvcount::$(wc -l < derivations.json)"
      - name: build ${{steps.eval-nixpkgs.outputs.drvcount}} derivations
        run: shuf derivations.json | nix shell .#build-drv -c xargs -P8 -d'\n' -I DRV build-drv "DRV"
      - name: upload derivations
        uses: actions/upload-artifact@v2
        with:
          name: derivations_${{matrix.worker_idx}}.json
          path: derivations.json
      - name: upload logs
        uses: actions/upload-artifact@v2
        with:
          name: logs_${{matrix.worker_idx}}
          path: logs
