on: push

name: CI/CD

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workers: [ 12 ]
        worker_idx: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 ]
    steps:
      - uses: actions/checkout@v2
      - uses: nixbuild/nix-quick-install-action@v2
        with:
          nix_version: 3.0pre20200829_f156513
          nix_conf: experimental-features = nix-command flakes
      - uses: nixbuild/nixbuild-action@v1
        with:
          nixbuild_ssh_key: ${{secrets.nixbuild_ssh_key}}

      - name: eval nixpkgs
        id: eval-nixpkgs
        run: |
          mkdir "worker_${{matrix.worker_idx}}" && cd "$_"
          nix eval --json --apply "f: f ${{matrix.workers}} ${{matrix.worker_idx}}" ..#jobSubset | jq -c ".[]" > derivations.json
          echo "::set-output name=drvcount::$(wc -l < derivations.json)"

      - name: build ${{steps.eval-nixpkgs.outputs.drvcount}} derivations
        working-directory: worker_${{matrix.worker_idx}}
        run: shuf derivations.json | nix shell ..#build-drv -c xargs -P8 -d'\n' -I DRV build-drv "DRV"

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: worker_${{matrix.worker_idx}}
          path: worker_${{matrix.worker_idx}}
