name: CI/CD

on: push

env:
  WORKERS: 24
  CONCURRENT_BUILDS_PER_WORKER: 8

defaults:
  run:
    shell: bash

jobs:
  setup:
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{steps.matrix.outputs.matrix}}
    steps:
      - uses: actions/checkout@v2
      - name: matrix
        id: matrix
        run: echo "::set-output name=matrix::$(./matrix.sh)"

  build:
    runs-on: ubuntu-20.04
    needs: setup
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.setup.outputs.matrix)}}
    name: Worker ${{matrix.worker_idx}} of ${{matrix.workers}}
    steps:
      - uses: actions/checkout@v2

      - uses: nixbuild/nix-quick-install-action@v4
        with:
          nix_version: 3.0pre20200829_f156513
          nix_conf: |
            experimental-features = nix-command flakes
            max-silent-time = 1800
            timeout = 3600

      - uses: nixbuild/nixbuild-action@v3
        with:
          nixbuild_ssh_key: ${{secrets.nixbuild_ssh_key}}
          cache-build-timeouts: true
          keep-builds-running: true

      - name: Evaluate all derivations
        id: eval-drvs
        run: |
          mkdir "worker_${{matrix.worker_idx}}" && cd "$_"
          nix eval --json ..#derivations | jq -c ".[]" > all_drvs.json
          split -n r/${{matrix.worker_idx}}/${{matrix.workers}} all_drvs.json > derivations.json
          # register a gc root for each derivation
          jq -r '.drvpath|values' derivations.json | xargs ln -sft /nix/var/nix/gcroots
          echo "::set-output name=drv_count_all::$(wc -l < all_drvs.json)"
          echo "::set-output name=drv_count_worker::$(wc -l < derivations.json)"

      - name: Build ${{steps.eval-drvs.outputs.drv_count_worker}} of ${{steps.eval-drvs.outputs.drv_count_all}} derivations
        working-directory: worker_${{matrix.worker_idx}}
        run: shuf derivations.json | nix shell ..#build-drvs -c build-drvs $CONCURRENT_BUILDS_PER_WORKER

      - name: Upload build results
        uses: actions/upload-artifact@v2
        with:
          name: worker_${{matrix.worker_idx}}
          path: worker_${{matrix.worker_idx}}
